# Generated by Django 5.1.7 on 2025-06-29 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rating_providerrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRating',
            fields=[
                ('rating_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.rating')),
                ('product_detail', models.CharField(max_length=60, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_rating', to='shop.product')),
            ],
            options={
                'abstract': False,
            },
            bases=('shop.rating', models.Model),
        ),
    ]
